# Generated by Django 4.1 on 2023-08-16 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_two', '0002_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
